; TODO INSERT CONFIG CODE HERE USING CONFIG BITS GENERATOR
;proyecto 2 comunicacion serial con computador

    ; PIC16F887 Configuration Bit Settings

; Assembly source line config statements

#include "p16f887.inc"

; CONFIG1
; __config 0xE0D4
 __CONFIG _CONFIG1, _FOSC_INTRC_NOCLKOUT & _WDTE_OFF & _PWRTE_OFF & _MCLRE_OFF & _CP_OFF & _CPD_OFF & _BOREN_OFF & _IESO_OFF & _FCMEN_OFF & _LVP_OFF
; CONFIG2
; __config 0xFFFF
 __CONFIG _CONFIG2, _BOR4V_BOR40V & _WRT_OFF
;interrupcion del timer 0 para controlar los displays
 
;constantes	
 VALOR_TMR0	EQU .6
 VARIA UDATA
;------------------------ DATOS O VISUALIZACION DE DATOS-----------------------------------------------
 CONTADOR RES	1;CUENTA EL BYTE QUE SE HA ENVIADO
MUX	RES	1 ;USADA PARA LA MULTIPLEXACION DE LOS DISPLAYS
X_LOW	RES	1;  GUARDAR LOS PRIMEROS DOS DIGITOS DE X
X_MID	RES	1;
X_HIGH	RES	1 ;GUARDA EL ULTIMO DIGITO
Y_LOW	RES	1 ; GUARDA LOS PRIMEROS DOS DIGITOS DE Y
Y_MID	RES	1;
Y_HIGH	RES	1;  GUARDA EL ULTIMO DIGITO DE Y
ADC_C0	RES	1 ;VALOR DEL ADC EN EL CANAL 3
ADC_C1	RES	1 ;VALOR DEL ADC EN EL CANAL 2
PIXEL_X_LOW RES	1; VALOR DEL PIXEL X PRIMER DIGITO
PIXEL_X_MID RES	1; DIGITO DE ENMEDIO
 PIXEL_X_HIGH RES    1; VALOR DEL PIXEL X ULTIMO DIGITO
PIXEL_Y_LOW RES	1; PRIMEROS DOS DIGITOS DEL PIXEL Y
PIXEL_Y_MID RES	1; DIGITO DE ENMEDIO DEL PIXEL Y
PIXEL_Y_HIGH RES    1; ULTIMO DIGITO DEL PIXEL Y
 ;---------------- CONTROL DE FLUJO DEL PROGRAMA--------------------------------------------------
 FLAGS	RES	1; BIT 0 : USADO PARA INDICAR QUE YA SE CONVIRTIO A BCD EL CANAL 0 ADC
		 ;  BIT 1: USADO PARA INDICAR QUE YA FUE CONVERTIDO A BCD EL CANAL 1 DEL ADC
 ;------------ VARIABLES USADAS EN CONVERTIDOR BINARIO A BCD------------------------------
 VALOR_BIN  RES 1
 VALOR_DECENAS RES 1
 VALOR_CENTENAS RES 1
 VALOR_UNIDADES RES 1
STATUS_RAM  RES	1
W_RAM	RES 1	
RES_VECT  CODE    0x0000            ; processor reset vector
    GOTO    START                   ; go to beginning of program

INTER CODE 0x0004
 SAVE:
    MOVWF   W_RAM
    SWAPF   STATUS,W
    MOVWF   STATUS_RAM
ISR:
    BTFSC INTCON,2  ;INTERRUPCION DEL TIMER 0
    GOTO    INT_TMR0
    BTFSC   PIR1,6 ;INTERRUPCION DEL ADC
    GOTO    INT_ADC
    BTFSC   PIR1,5   ;INTERRUPCION EUSART RECEIVER
    GOTO    INT_RC
    
INT_TMR0:
    BCF	INTCON,2
    MOVLW   VALOR_TMR0
    MOVWF   TMR0
    CALL MOSTRAR_DATOS
    INCF    MUX,F
    GOTO LOAD
INT_ADC:
    BCF	PIR1,6 ;SE LIMPIA LA BANDERA
    MOVF    ADRESH,W
    
    BTFSS   ADCON0,2 ;SI ESTE BIT ES CERO SE ESTABA LEYENDO EL CANAL 3
    GOTO LECTURA_C1
    
    MOVWF ADC_C1
    BCF	ADCON0,2 ;SE CAMBIA AL CANAL 1
    GOTO    FINAL
    
    LECTURA_C1
    MOVWF   ADC_C0
    BSF	ADCON0,2 ;SE CAMBIA AL CANAL 0
    
    FINAL
    NOP
    NOP
    NOP
    NOP
    NOP ;REQUERIMIENTOS DE ADQUISICION
    BSF	ADCON0,1 ;INICIA LA CONVERSION
    GOTO LOAD
INT_RC:
LOAD:
    SWAPF   STATUS_RAM,W
    MOVWF   STATUS
    SWAPF   W_RAM,F
    SWAPF   W_RAM,W
    RETFIE
    
 
TABLA:
    ANDLW   B'00001111' ;MASCARA
    ADDWF   PCL,F
    RETLW	 B'00001000' ;0 ANODO
    RETLW	 B'01101011' ;1
    RETLW  B'00100100' ;2
    RETLW  B'00100001' ;3
    RETLW  B'01000011' ;4
    RETLW  B'00010001' ;5
    RETLW  B'00010000' ;6
    RETLW  B'00101011' ;7
    RETLW B'00000000' ;8
    RETLW B'00000001' ;9
    
 MOSTRAR_DATOS:
    CLRF    PORTB
    MOVF    MUX, W
    ADDWF PCL,F
    
    GOTO PRIMERO
    GOTO SEGUNDO
    GOTO TERCERO
    GOTO CUARTO
    GOTO QUINTO
    GOTO SEXTO
    CLRF   MUX
    
    PRIMERO
    MOVF   PIXEL_Y_LOW,W
    CALL    TABLA
    MOVWF   PORTD
    BSF	PORTB,0
    RETURN
    
    SEGUNDO
    MOVF   PIXEL_Y_MID,W
    CALL  TABLA
    MOVWF   PORTD
    BSF	PORTB,1
    RETURN
    
    TERCERO
    MOVF    PIXEL_Y_HIGH,W
    CALL TABLA
    MOVWF   PORTD
    BSF	PORTB,2
    RETURN
    
    CUARTO
    MOVF    PIXEL_X_LOW,W
    CALL TABLA
    MOVWF   PORTD
    BSF	PORTB,3
    RETURN
    
    QUINTO
    MOVF    PIXEL_X_MID,W
    CALL TABLA
    MOVWF   PORTD
    BSF	PORTB,4
    RETURN
    
    SEXTO
    MOVF    PIXEL_X_HIGH,W
    CALL TABLA
    MOVWF   PORTD
    BSF	PORTB,5
    RETURN
    
MAIN_PROG CODE                      ; let linker place main program

START
    BSF	STATUS,6
    BSF	STATUS,5 ;BANCO 3
    
    CLRF    ANSELH ;PUERTO B COMO SALIDA DIGITAL
    MOVLW   .255
    MOVWF   ANSEL ;PUERTO A Y E COMO ENTRADA DIGITAL
    
    BCF	STATUS,6 ;BANCO 1
    
    MOVLW   .255
    MOVWF   TRISA
    CLRF    TRISB
    CLRF    TRISD
    
    MOVLW   B'10000001' ; EN LO QUE INTERESA, EL PRESCALER DEL TMR 0 SE COLOCA EN 1:4 Y LA FUENTE ES EL OSCILADOR INTERNO
    MOVWF   OPTION_REG ;
    
    MOVLW   B'11100000' ;INTERRUPCIONES GLOBALES, PERIFERICAS ACTIVADAS, TMR0 INT ACTIVADA
    MOVWF   INTCON
    
    BSF	PIE1,6 ;INTERRUPCION DEL ADC ACTIVADA
    ;BSF	PIE1,5 ;INTERRUPCION EUSART RECEIVER ACTIVADA
    
    BCF	TXSTA,6 ;TRANSMISION DE 8 BITS
    BSF	TXSTA,5 ;TRANSMISION ACTIVADA
    BCF	TXSTA,4 ;MODO ASINCRONO
    BSF	TXSTA,2 ;BAUD RATE DE ALTA VELOCIDAD
    
    MOVLW   .23
    MOVWF   SPBRG ;BAUD RATE DE 10417
    
    BCF	ADCON1,7 ;JUSTIFICADO A LA DERECHA
    BCF	ADCON1,5 ; V++ COMO VCC
    BCF	ADCON1,4   ;V-- COMO VDD
    
    BCF	STATUS,5 ;BANCO 0
    
    MOVLW   B'01000001' ;FOSC/8 CANAL AN0  Y SE ENCIENDE
    MOVWF   ADCON0
    
    MOVLW   VALOR_TMR0
    MOVWF   TMR0    
    
    BSF	RCSTA,7 ;SE CONFIGURA EL PUERTO SERIAL
    BCF	RCSTA,6 ;RECEPCION DE 8 BITS
    BSF	RCSTA,4 ;RECEPCION CONTINUA
    
    BSF	ADCON0,1 ;INICIA LA CONVERSION DEL ADC
   CLRF	PIXEL_X_LOW
   CLRF	PIXEL_X_MID
   CLRF	PIXEL_X_HIGH
   CLRF	PIXEL_Y_LOW
   CLRF	PIXEL_Y_MID
   CLRF	PIXEL_Y_HIGH
   CLRF	MUX
   CLRF	ADC_C1
   CLRF	ADC_C0
   CLRF	CONTADOR
   
LOOP:
    MOVF    ADC_C0,W
    MOVWF   VALOR_BIN
    CALL    CONVERTIR_BIN_TO_BCD
    MOVF    VALOR_CENTENAS,W
    MOVWF  PIXEL_X_HIGH
    MOVWF   X_HIGH
    MOVF    VALOR_DECENAS,W
    MOVWF   PIXEL_X_MID
    MOVWF   X_MID
    MOVF    VALOR_UNIDADES,W
    MOVWF   PIXEL_X_LOW
    MOVWF   X_LOW
    
    MOVF    ADC_C1,W
    MOVWF   VALOR_BIN
    CALL    CONVERTIR_BIN_TO_BCD
    MOVF    VALOR_CENTENAS,W
    MOVWF  PIXEL_Y_HIGH
    MOVWF   Y_HIGH
    MOVF    VALOR_DECENAS,W
    MOVWF   PIXEL_Y_MID
    MOVWF   Y_MID
    MOVF    VALOR_UNIDADES,W
    MOVWF   PIXEL_Y_LOW
    MOVWF   Y_LOW
    
    CALL ENVIAR_DATOS
    
    GOTO LOOP

    
ENVIAR_DATOS:
    BTFSS   PIR1,4 ;SI NO ESTA OCUPADO SE SALTA EL RETURN
    RETURN
   
    ;----- SE DETERMINA QUE DATO HAY QUE ENVIAR -------------------------------
    MOVF    CONTADOR,W
    ADDWF   PCL,F
    GOTO    UNO
    GOTO    DOS
    GOTO    TRES
    GOTO    CUATRO
    GOTO    CINCO
    GOTO    SEIS
    GOTO    SIETE
    GOTO    OCHO
    CLRF    CONTADOR
    UNO
    MOVF    X_HIGH,W
    ADDLW   .48 ;SE PASA DE BCD A ASCII
    MOVWF   TXREG
    INCF    CONTADOR,F
    RETURN
    
    DOS
     MOVF    X_MID,W
    ADDLW   .48 ;SE PASA DE BCD A ASCII
    MOVWF   TXREG
    INCF    CONTADOR,F
    RETURN
    
    TRES
    MOVF    X_LOW,W
    ADDLW   .48 ;SE PASA DE BCD A ASCII
    MOVWF   TXREG
    INCF    CONTADOR,F
    RETURN
    
    CUATRO
    MOVLW    .44 ; COMA EN ASCII
    MOVWF   TXREG
    INCF    CONTADOR,F
    RETURN
    
    CINCO
     MOVF    Y_HIGH,W
    ADDLW   .48 ;SE PASA DE BCD A ASCII
    MOVWF   TXREG
    INCF    CONTADOR,F
    RETURN
    
    SEIS
    MOVF    Y_MID,W
    ADDLW   .48 ;SE PASA DE BCD A ASCII
    MOVWF   TXREG
    INCF    CONTADOR,F
    RETURN
    
    SIETE
     MOVF    Y_LOW,W
    ADDLW   .48 ;SE PASA DE BCD A ASCII
    MOVWF   TXREG
    INCF    CONTADOR,F
    RETURN
    
    OCHO
    MOVLW   .10 ;NUEVA LINEA
    MOVWF   TXREG
    INCF    CONTADOR,F
    RETURN  
    
    
    
CONVERTIR_BIN_TO_BCD:
    CLRF    VALOR_CENTENAS
    CLRF    VALOR_DECENAS
    CLRF    VALOR_UNIDADES
    ;PRIMERO SE INICIA CON LAS CENTENAS
    CENTENAS
    MOVLW   .100
    SUBWF   VALOR_BIN,W    ;EN EL FSR SE COLOCA LA DIRECCION DEL VALOR A CONVERTIR
    BTFSS   STATUS, C	; SI EL BIT C ES 1 QUIERE DECIR QUE INDF >= W 
    GOTO    DECENAS ;SI EL BIT ES CERO ES EJECUTA ESTO, LO QUE QUIERE DECIR QUE YA EL NUMEOR EN INDF
    ;ES MENOR O IGUAL A 100
    
    INCF    VALOR_CENTENAS,F
    MOVWF   VALOR_BIN
    GOTO CENTENAS ;VUELVE A RESTAR
    
    
    DECENAS
    MOVLW   .10
    SUBWF   VALOR_BIN,W
    BTFSS   STATUS,C  ;LO MISMO QUE CON CENTENAS 
    GOTO UNIDADES
    
    INCF    VALOR_DECENAS,F
    MOVWF   VALOR_BIN
    GOTO DECENAS
    
    UNIDADES
    MOVLW .1
    SUBWF   VALOR_BIN,W
    BTFSS   STATUS,C ;MISMA LOGICA QUE ANTERIORMENTE
    RETURN
    
    INCF    VALOR_UNIDADES,F
    MOVWF VALOR_BIN
    GOTO UNIDADES
    
    END